name: Build and Deploy Backend to Minikube

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: manulperera5665/heronsocialmediaplatform-backend
  IMAGE_TAG: ${{ github.sha }}
  FULL_IMAGE_NAME: manulperera5665/heronsocialmediaplatform-backend:${{ github.sha }}
  KUBE_DEPLOYMENT: heronsocialmedia-backend
  KUBE_NAMESPACE: default
  CONTAINER_NAME: heronsocialmedia-backend  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show files (debug)
        run: ls -al

      - name: Docker login to Docker Hub
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t $FULL_IMAGE_NAME .

      - name: Push Image to Docker Hub
        run: docker push $FULL_IMAGE_NAME
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Update Kubernetes Deployment Image
        run: |
          kubectl set image deployment/$KUBE_DEPLOYMENT $CONTAINER_NAME=$FULL_IMAGE_NAME -n $KUBE_NAMESPACE
