name: Build and Deploy Backend to Minikube

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: manulperera5665/heronsocialmediaplatform-backend
  IMAGE_TAG: latest
  FULL_IMAGE_NAME: manulperera5665/heronsocialmediaplatform-backend:latest
  KUBE_DEPLOYMENT: heronsocialmedia-backend
  KUBE_NAMESPACE: default
  CONTAINER_NAME: heronsocialmedia-backend  

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show files (debug)
        run: Get-ChildItem -Force
        shell: powershell

      - name: Docker login to Docker Hub
        run: docker login -u $env:DOCKERHUB_USERNAME -p $env:DOCKERHUB_TOKEN
        shell: powershell
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build --no-cache -t $env:FULL_IMAGE_NAME .
        shell: powershell

      - name: Push Docker image to Docker Hub
        run: docker push $env:FULL_IMAGE_NAME
        shell: powershell

      - name: Update Kubernetes deployment image
        run: |
          kubectl set image deployment/$env:KUBE_DEPLOYMENT $env:CONTAINER_NAME=$env:FULL_IMAGE_NAME -n $env:KUBE_NAMESPACE
        shell: powershell
