name: Build CI/CD pipeline for backend

on:
  push:
    branches:
      - main   # No space between "-" and "main"

env:
  DOCKER_IMAGE: heronsocialmediaplatform-backend:latest
  KUBE_DEPLOYMENT: heronsocialmedia-backend
  KUBE_NAMESPACE: default

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t $DOCKER_IMAGE .

      - name: Load Image to Minikube
        run: |
          minikube image load $DOCKER_IMAGE

      - name: Restart Deployment
        run: |
          kubectl rollout restart deployment $KUBE_DEPLOYMENT -n $KUBE_NAMESPACE
