name: Build CI/CD pipeline for backend

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: heronsocialmediaplatform-backend:latest
  KUBE_DEPLOYMENT: heronsocialmedia-backend
  KUBE_NAMESPACE: default

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Show files for debugging
        run: Get-ChildItem -Force
        shell: powershell

      - name: Check Docker info
        run: docker info

      - name: Build Docker Image
        run: docker build --no-cache -t $env:DOCKER_IMAGE .
        shell: powershell


      - name: Load Image to Minikube
        run: minikube image load $env:DOCKER_IMAGE
        shell: powershell

      - name: Restart Deployment
        run: kubectl rollout restart deployment $env:KUBE_DEPLOYMENT -n $env:KUBE_NAMESPACE
        shell: powershell

